name: Generate Snake

on:
  schedule:
    - cron: "0 */6 * * *" # Executa a cada 6 horas

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do repositório
        uses: actions/checkout@v2

      - name: Gere a cobrinha
        uses: Platane/snk@master
        with:
          github_user_name: wildyhunter
          gif_out_path: dist/github-contribution-grid-snake.gif
          svg_out_path: dist/github-contribution-grid-snake.svg

      - name: Adicione e confirme mudanças
        run: |
          git config --global user.email "you@example.com"
          git config --global user.name "Your Name"
          git add dist/github-contribution-grid-snake.gif dist/github-contribution-grid-snake.svg
          git commit -m "Add snake animation"
          git push

      - name: Deploy para GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: dist
